version: "3.8"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    entrypoint: >
      sh -c "
      ollama serve & 
      sleep 5 && 
      ollama pull tinyllama && 
      wait
      "

volumes:
  ollama_data: